### ISSUE TITLE
Он работает 

### ISSUE THREAD

**Issue by alexe-lfg** [Assasans/TXServer-Public#1]
Он работает а то они же закрылись

**Comment by C6OI** [comment]
> Он работает а то они же закрылись
https://user-images.githubusercontent.com/59257047/140074152-66915da4-8192-4625-9325-994ce64105cf.mp4

**Comment by C6OI** [comment]
> Он работает а то они же закрылись

[https://media.discordapp.net/attachments/821747385112985610/905455447115448360/neznal.mp4]()

**Comment by C6OI** [comment]
https://user-images.githubusercontent.com/59257047/140074564-5aff0d9a-793d-4cd2-ae58-ebc05f1dd073.mp4

Почему видосы не работают нормально

**Comment by C6OI** [comment]
> Он работает а то они же закрылись


https://user-images.githubusercontent.com/59257047/140074747-8ac61215-ef48-49df-94dc-6dfdcbcf9647.mp4

**Comment by Donatik3310** [comment]
как запустить если нету exe???

**Comment by Kammunist** [comment]
Простите не видел. После сборки проекта у в папке bin будет лежать exe файл. Отправлено с моего телефона Huawei-------- Исходное сообщение --------От: Donatik3310 ***@***.***>Дата: сб, 9 сент. 2023 г., 17:57Кому: Assasans/TXServer-Public ***@***.***>Копия: Subscribed ***@***.***>Тема: Re: [Assasans/TXServer-Public] Он работает  (Issue #1)
как запустить если нету exe???

**Comment by Donatik3310** [comment]
а если exe нету и папки bin тоже

**Comment by C6OI** [comment]
прочитать readme: ❌

**Comment by Donatik3310** [comment]
нету XServerConsole/bin/Debug/net5.0
![Снимок экрана (1001)](https://github.com/Assasans/TXServer-Public/assets/122474741/7b85c650-882a-46c1-b5ca-5507d91f1ecc)

**Comment by Donatik3310** [comment]
да ив вообще папки с exe

**Comment by C6OI** [comment]
прочитать readme: ❌

**Comment by Donatik3310** [comment]
прочитал раз 10, файл нашел, но он не exe...

**Comment by C6OI** [comment]
ещё раз прочитай

**Comment by Donatik3310** [comment]
как я правильно понимаю меня должно щас интересовать это? 
Сборка и запуск
Сборка:

dotnet build TXServerConsole.
cd TXServerConsole/bin/Debug/net5.0.

Запуск:

TXServerConsole.exe --run <адрес> <порт> <max players>.
10 максимальных игроков: TXServerConsole.exe --run 0.0.0.0 5050 10.
Loopback, 5 максимальных игроков: TXServerConsole.exe --run 127.0.0.1 5050 5.

**Comment by Donatik3310** [comment]
вот этого (((TXServerConsole.exe --run 127.0.0.1 5050 5.))) нету

**Comment by Donatik3310** [comment]
the exe file does not work
